package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/UPwith-me/Container-Maker/pkg/workspace"
	"github.com/spf13/cobra"
)

var workspaceCmd = &cobra.Command{
	Use:   "workspace",
	Short: "Manage workspace configuration",
	Long: `Manage multi-service workspace configuration.

A workspace allows you to define and orchestrate multiple services together,
with dependencies, shared networks, and coordinated lifecycle management.

COMMANDS
  cm workspace init         Create a new cm-workspace.yaml
  cm workspace validate     Validate workspace configuration
  cm workspace graph        Show dependency graph
  cm workspace services     List defined services`,
	Aliases: []string{"ws"},
}

var wsInitCmd = &cobra.Command{
	Use:   "init [name]",
	Short: "Initialize a new workspace",
	Long: `Create a new cm-workspace.yaml in the current directory.

This creates a starter configuration file that you can customize
for your project's services.

EXAMPLES
  cm workspace init
  cm workspace init my-project`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		// Check if file already exists
		if _, err := os.Stat(workspace.DefaultConfigFile); err == nil {
			fmt.Printf("❌ %s already exists\n", workspace.DefaultConfigFile)
			return nil
		}

		// Determine name
		var name string
		if len(args) > 0 {
			name = args[0]
		} else {
			cwd, _ := os.Getwd()
			name = filepath.Base(cwd)
		}

		if name == "" {
			name = "my-workspace"
		}

		// Create default workspace
		ws := workspace.CreateDefaultWorkspace(name)

		// Add example services
		ws.Services["frontend"] = &workspace.Service{
			Template: "node",
			Path:     "./frontend",
			Ports: []workspace.PortConfig{
				{Target: 3000, Published: 3000},
			},
			DependsOn: []string{"backend"},
		}

		ws.Services["backend"] = &workspace.Service{
			Template: "python",
			Path:     "./backend",
			Ports: []workspace.PortConfig{
				{Target: 8000, Published: 8000},
			},
			DependsOn: []string{"database"},
			Environment: map[string]string{
				"DATABASE_URL": "postgres://postgres:postgres@database:5432/app",
			},
		}

		ws.Services["database"] = &workspace.Service{
			Image: "postgres:15",
			Ports: []workspace.PortConfig{
				{Target: 5432, Published: 5432},
			},
			Environment: map[string]string{
				"POSTGRES_USER":     "postgres",
				"POSTGRES_PASSWORD": "postgres",
				"POSTGRES_DB":       "app",
			},
		}

		// Write file
		content := fmt.Sprintf(`# Container-Maker Workspace Configuration
# Generated by 'cm workspace init'

name: %s
version: "1.0"

# Default settings for all services
defaults:
  restart: unless-stopped

# Service definitions
services:
  frontend:
    template: node
    path: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    template: python
    path: ./backend
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/app

  database:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    # volumes:
    #   - db-data:/var/lib/postgresql/data

# Network configuration (optional)
networks:
  default:
    driver: bridge

# Volume configuration (optional)
# volumes:
#   db-data:
`, name)

		if err := os.WriteFile(workspace.DefaultConfigFile, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write config: %w", err)
		}

		fmt.Printf("✅ Created %s\n", workspace.DefaultConfigFile)
		fmt.Println()
		fmt.Println("Next steps:")
		fmt.Println("  1. Edit cm-workspace.yaml to define your services")
		fmt.Println("  2. Run 'cm up' to start all services")
		fmt.Println("  3. Run 'cm ps' to see service status")

		return nil
	},
}

var wsValidateCmd = &cobra.Command{
	Use:   "validate",
	Short: "Validate workspace configuration",
	RunE: func(cmd *cobra.Command, args []string) error {
		ws, err := workspace.Load("")
		if err != nil {
			fmt.Printf("❌ %v\n", err)
			return nil
		}

		if err := workspace.Validate(ws); err != nil {
			fmt.Printf("❌ Invalid: %v\n", err)
			return nil
		}

		fmt.Printf("✅ Workspace '%s' is valid\n", ws.Name)
		fmt.Printf("   Services: %d\n", len(ws.Services))
		return nil
	},
}

var wsGraphCmd = &cobra.Command{
	Use:   "graph",
	Short: "Show dependency graph",
	RunE: func(cmd *cobra.Command, args []string) error {
		ws, err := workspace.Load("")
		if err != nil {
			fmt.Printf("❌ %v\n", err)
			return nil
		}

		graph, err := workspace.NewGraph(ws)
		if err != nil {
			fmt.Printf("❌ %v\n", err)
			return nil
		}

		fmt.Println(graph.Visualize())

		startOrder, err := graph.StartOrder()
		if err != nil {
			fmt.Printf("❌ %v\n", err)
			return nil
		}

		fmt.Println("Start order:")
		for i, name := range startOrder {
			fmt.Printf("  %d. %s\n", i+1, name)
		}

		return nil
	},
}

var wsServicesCmd = &cobra.Command{
	Use:   "services",
	Short: "List defined services",
	RunE: func(cmd *cobra.Command, args []string) error {
		ws, err := workspace.Load("")
		if err != nil {
			fmt.Printf("❌ %v\n", err)
			return nil
		}

		fmt.Printf("Workspace: %s\n\n", ws.Name)
		fmt.Printf("%-15s %-20s %-15s %-20s\n", "SERVICE", "IMAGE/TEMPLATE", "DEPENDS_ON", "PORTS")
		fmt.Printf("%-15s %-20s %-15s %-20s\n", "-------", "--------------", "----------", "-----")

		for name, svc := range ws.Services {
			img := svc.Image
			if img == "" {
				img = svc.Template
			}
			if len(img) > 18 {
				img = img[:15] + "..."
			}

			deps := "-"
			if len(svc.DependsOn) > 0 {
				deps = fmt.Sprintf("%v", svc.DependsOn)
				if len(deps) > 13 {
					deps = deps[:10] + "..."
				}
			}

			ports := "-"
			if len(svc.Ports) > 0 {
				ports = fmt.Sprintf("%d", svc.Ports[0].Target)
			}

			fmt.Printf("%-15s %-20s %-15s %-20s\n", name, img, deps, ports)
		}

		return nil
	},
}

func init() {
	workspaceCmd.AddCommand(wsInitCmd)
	workspaceCmd.AddCommand(wsValidateCmd)
	workspaceCmd.AddCommand(wsGraphCmd)
	workspaceCmd.AddCommand(wsServicesCmd)

	rootCmd.AddCommand(workspaceCmd)
}
